### ISSUE TITLE
An exception when running program

### ISSUE THREAD

**Issue by roozbehid** [keeper013/CrossCutterN#6]
I most often get this exception.
Do you have any idea? I am using your samples but weaving everything...

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: nameSpace
   at CrossCutterN.Base.Metadata.Execution..ctor(String assemblyFullName, String nameSpace, String classFullName, String className, Int32 hashCode, String fullName, String name, String returnType)
   at CrossCutterN.Base.Metadata.MetadataFactory.InitializeExecution(String assemblyFullName, String nameSpace, String classFullName, String className, Int32 hashCode, String fullName, String name, String returnType)

**Comment by keeper013** [comment]
Hi RoozBehid:

Thanks for your feedback. Could you please send the source code or dll that triggers this issue, together with your CrossCutterN configuration files to keeper013@gmail.com? So I can reproduce and fix the issue?

Thanks.

**Comment by keeper013** [comment]
no following up.
